### ISSUE TITLE
An error while loading the config

### ISSUE THREAD

**Issue by Dellism** [maxsupermanhd/WebChunk#2]
So i cloned the repo, ran `go build`, renamed `example_config.json` to `config.json`, and launched executable. although it gives me an error:
`main.go:136: Error loading config file: json: cannot unmarshal array into Go struct field WebChunkConfig.proxy_routing of type map[string]main.ProxyRoute`
I am not familiar with go, so i might be doing something wrong, can anyone help?

**Comment by maxsupermanhd** [comment]
Oh it is nothing wrong from your side, it is just I am being lazy on updating example configuration.

Whole thing is under heavy development now and requires *some* understanding of what is going on. Currently there is no easy way of adding chunks to the system even, I am trying to make a proxy that will capture terrain (like mircokroon's [world downloader](https://github.com/mircokroon/minecraft-world-downloader)) but so far nothing really working, not even close.

I will update everything once it will be usable-ish, will make (or update is correct word since I already made it) a fabric mod that will allow client to interact with chunk storages and maybe render a map in-game. Also right now I am busy with my university so it may be a bit of time before some more progress will be made.

If you want to discuss something in-depth or want me to explain something in voice feel free to join Tnze's discord: https://discord.gg/EjGr68UEUh

**Comment by maxsupermanhd** [comment]
I updated example config, try now

**Comment by Dellism** [comment]
Now it is working, thanks. I'm looking forward for future releases!
